---
- hosts: all
#  become: true
  tasks:
    - name: set additional vars
      set_fact:
        resolved_env: "{{ (env == 'prod') | ternary('prod', 'sandbox') }}"
    - name: Include environment specific vars
      include_vars: "env_vars/{{ resolved_env }}.yml"

- hosts: all
  become: true
  vars:
    jenkins_enable_security: false
    jenkins_master_executors: 0
    jenkins_plugins:
      - { name: ace-editor, version: "1.1" }
      - { name: ansicolor, version: "0.5.2" }
      - { name: ant, version: "1.8" }
      - { name: antisamy-markup-formatter, version: "1.5" }
      - { name: apache-httpcomponents-client-4-api, version: "4.5.3-2.1" }
      - { name: authentication-tokens, version: "1.3" }
      - { name: azure-commons, version: "0.2.5" }
      - { name: azure-credentials, version: "1.6.0" }
      - { name: azure-keyvault, version: "0.9.5-hmcts.4" }
      - { name: azure-vm-agents, version: "0.7.0" }
      - { name: blueocean, version: "1.5.0" }
      - { name: blueocean-autofavorite, version: "1.2.2" }
      - { name: blueocean-bitbucket-pipeline, version: "1.5.0" }
      - { name: blueocean-commons, version: "1.5.0" }
      - { name: blueocean-config, version: "1.5.0" }
      - { name: blueocean-core-js, version: "1.5.0" }
      - { name: blueocean-dashboard, version: "1.5.0" }
      - { name: blueocean-display-url, version: "2.2.0" }
      - { name: blueocean-events, version: "1.5.0" }
      - { name: blueocean-git-pipeline, version: "1.5.0" }
      - { name: blueocean-github-pipeline, version: "1.5.0" }
      - { name: blueocean-i18n, version: "1.5.0" }
      - { name: blueocean-jira, version: "1.5.0" }
      - { name: blueocean-jwt, version: "1.5.0" }
      - { name: blueocean-personalization, version: "1.5.0" }
      - { name: blueocean-pipeline-api-impl, version: "1.5.0" }
      - { name: blueocean-pipeline-editor, version: "1.5.0" }
      - { name: blueocean-pipeline-scm-api, version: "1.5.0" }
      - { name: blueocean-rest, version: "1.5.0" }
      - { name: blueocean-rest-impl, version: "1.5.0" }
      - { name: blueocean-web, version: "1.5.0" }
      - { name: bouncycastle-api, version: "2.16.2" }
      - { name: branch-api, version: "2.0.20" }
      - { name: build-monitor-plugin, version: "1.12+build.201708172343" }
      - { name: cloud-stats, version: "0.18" }
      - { name: cloudbees-bitbucket-branch-source, version: "2.2.11" }
      - { name: cloudbees-folder, version: "6.4" }
      - { name: command-launcher, version: "1.2" }
      - { name: credentials, version: "2.1.16" }
      - { name: credentials-binding, version: "1.16" }
      - { name: custom-tools-plugin, version: "0.5" }
      - { name: display-url-api, version: "2.2.0" }
      - { name: docker-commons, version: "1.11" }
      - { name: docker-workflow, version: "1.15.1" }
      - { name: durable-task, version: "1.23-rc134.ab9d0d85cdd8" }
      - { name: extended-choice-parameter, version: "0.76" }
      - { name: external-monitor-job, version: "1.7" }
      - { name: favorite, version: "2.3.1" }
      - { name: gatling, version: "1.2.2" }
      - { name: git, version: "3.8.0" }
      - { name: git-client, version: "2.7.1" }
      - { name: git-server, version: "1.7" }
      - { name: github, version: "1.29.0" }
      - { name: github-api, version: "1.90" }
      - { name: github-branch-source, version: "2.3.6" }
      - { name: greenballs, version: "1.15" }
      - { name: handlebars, version: "1.1.1" }
      - { name: handy-uri-templates-2-api, version: "2.1.6-1.0" }
      - { name: htmlpublisher, version: "1.15" }
      - { name: http_request, version: "1.8.22" }
      - { name: jackson2-api, version: "2.8.11.1" }
      - { name: jacoco, version: "3.0.1" }
      - { name: javadoc, version: "1.4" }
      - { name: jdk-tool, version: "1.1" }
      - { name: jenkins-design-language, version: "1.5.0" }
      - { name: jira, version: "2.5" }
      - { name: jquery, version: "1.12.4-0" }
      - { name: jquery-detached, version: "1.2.1" }
      - { name: jsch, version: "0.1.54.2" }
      - { name: junit, version: "1.24" }
      - { name: ldap, version: "1.20" }
      - { name: lockable-resources, version: "2.2" }
      - { name: mailer, version: "1.21" }
      - { name: matrix-auth, version: "2.2" }
      - { name: matrix-project, version: "1.13" }
      - { name: maven-plugin, version: "3.1.2" }
      - { name: mercurial, version: "2.3" }
      - { name: momentjs, version: "1.1.1" }
      - { name: pam-auth, version: "1.3" }
      - { name: pipeline-build-step, version: "2.7" }
      - { name: pipeline-github-lib, version: "1.0" }
      - { name: pipeline-graph-analysis, version: "1.6" }
      - { name: pipeline-input-step, version: "2.8" }
      - { name: pipeline-milestone-step, version: "1.3.1" }
      - { name: pipeline-model-api, version: "1.2.8" }
      - { name: pipeline-model-declarative-agent, version: "1.1.1" }
      - { name: pipeline-model-definition, version: "1.2.8" }
      - { name: pipeline-model-extensions, version: "1.2.8" }
      - { name: pipeline-rest-api, version: "2.10" }
      - { name: pipeline-stage-step, version: "2.3" }
      - { name: pipeline-stage-tags-metadata, version: "1.2.8" }
      - { name: pipeline-stage-view, version: "2.10" }
      - { name: pipeline-utility-steps, version: "2.1.0" }
      - { name: plain-credentials, version: "1.4" }
      - { name: pubsub-light, version: "1.12" }
      - { name: run-condition, version: "1.0" }
      - { name: saml, version: "1.0.5" }
      - { name: sauce-ondemand, version: "1.176" }
      - { name: scm-api, version: "2.2.7" }
      - { name: script-security, version: "1.43" }
      - { name: slack, version: "2.3" }
      - { name: sonar, version: "2.7.1" }
      - { name: sse-gateway, version: "1.15" }
      - { name: ssh-credentials, version: "1.13" }
      - { name: structs, version: "1.14" }
      - { name: timestamper, version: "1.8.9" }
      - { name: token-macro, version: "2.5" }
      - { name: variant, version: "1.1" }
      - { name: windows-slaves, version: "1.3.1" }
      - { name: workflow-aggregator, version: "2.5" }
      - { name: workflow-api, version: "2.27" }
      - { name: workflow-basic-steps, version: "2.6" }
      - { name: workflow-cps, version: "2.53" }
      - { name: workflow-cps-global-lib, version: "2.9" }
      - { name: workflow-durable-task-step, version: "2.19" }
      - { name: workflow-job, version: "2.21" }
      - { name: workflow-multibranch, version: "2.19" }
      - { name: workflow-scm-step, version: "2.6" }
      - { name: workflow-step-api, version: "2.14" }
      - { name: workflow-support, version: "2.18" }

    jenkins_manual_plugins:
      - file_name: 'azure-keyvault.hpi'
        checksum: 'sha256:556a8491a092bc743e874534247cf3f0cf94c91222434f0111a55129319ea94e'
        url: 'https://github.com/hmcts/azure-keyvault-plugin/releases/download/0.9.5-hmcts.4/azure-keyvault.hpi'

    pipeline_jobs: []

    slack_domain: 'hmcts-reform'
    slack_credential_id: 'slack-token'

    jenkins_credentials:
        - id: jenkins-github-api-token
          type: cred-usrpwd
          description: "Jenkins GitHub credentials (Username/password format)"
          username: "moj-jenkins-user"
          password: "{{ github_apikey }}"
        - id: jenkins-github-api-token-secret-text
          type: cred-secret-text
          description: "moj-jenkins-user Public Github API Token (Used by the Github plugin for managing webhooks)"
          password: "{{ github_apikey }}"
        - id: jenkins-github-hmcts-api-token
          type: cred-usrpwd
          description: "Jenkins HMCTS GitHub credentials (Username/password format)"
          username: "{{ api_key_username }}"
          password: "{{ hmcts_github_apikey }}"
        - id: github-enterprise-token
          type: cred-usrpwd
          username: "github-enterprise-token"
          password: "{{ github_enterprise_apikey }}"
          description: "Github Enterprise API token from cnpjenkins AD service account"
        - id: github-enterprise-token-secret-text
          type: cred-secret-text
          description: "cnpjenkins service account GitHub Enterprise API Token (Used by the Github plugin for managing webhooks)"
          password: "{{ github_enterprise_apikey }}"
        - id: git_access_ssh_key
          type: cred-usrkey
          description: "Credential ID: git_access_key"
          username: "moj-jenkins-user"
        - id: vm_agent_creds
          type: cred-usrpwd
          description: "SSH credentials for Jenkins agents"
          username: "{{ jenkins_agent_user }}"
          password: "{{ jenkins_agent_password }}"
        - id: '{{ slack_credential_id }}'
          type: cred-secret-text
          description: "Slack token"
          password: "{{ slack_token }}"
        - id: COSMOSDB_TOKEN_KEY
          type: cred-secret-text
          description: "Read/Write Key To Publish CosmosDB Metrics"
          password: "{{ pipelinemetrics_cosmosdb_key }}"
        - id: owasp-db-login
          type: cred-usrpwd
          description: "Username and password for the OWASP vulnerability database"
          username: "owasp_administrator"
          password: "{{ owaspdb_password }}"
        - id: buildlog-storage-account
          type: cred-usrpwd
          description: "Storage account name and access key for storing build reports"
          username: "{{ buildlog_sa_name }}"
          password: "{{ buildlog_sa_key }}"

    jenkins_global_pipeline_libraries:
        - name: "Infrastructure"
          remote: "git@github.com:hmcts/moj-jenkins-library.git"
          credentials_id: "git_access_ssh_key"
          include: "*"
          excludes: ""
          ignore_on_push_notifications: true
          default_version: "master"
          set_implicit: false
          allow_version_override: true
    jenkins_build_monitor_views:
      - {
          name: "SSCS Dashboard",
          jobs: ["HMCTS/sscs-case-loader/master", "HMCTS/submit-your-appeal/master", "HMCTS/track-your-appeal-frontend/master", "HMCTS/track-your-appeal-notifications/master", "HMCTS/tribunals-case-api/master"],
          title: "SSCS Dashboard"
        }

    terraform_version: 0.11.3
    terraform_sha256sum: 6b8a7b83954597d36bbed23913dd51bc253906c612a070a21db373eab71b277b

    sonar_server_url: "https://sonar.reform.hmcts.net"

    # Variables specific to azure-vm-agent plugin
    jenkins_home: /opt/jenkins
    jenkins_agent_user: "jenkinsssh"
    jenkins_agent_cloud_name: "moj-azure"
    jenkins_agent_azure_sp_id: "jenkinsServicePrincipal"
    jenkins_agent_vm_limit: "10"
    jenkins_agent_deployment_timeout: "1200"
    jenkins_agent_storage_type: "Standard_LRS"
    jenkins_agent_machine_size: "Standard_D4_v3"
    jenkins_agent_vm_creds: "vm_agent_creds"
    jenkins_agent_template_name: "moj-jenkins-builders"
    jenkins_agent_labels: ""
    jenkins_agent_executors: "4"
    jenkins_agent_jvm_options: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1"
    jenkins_agent_private_ip: true

    # JVM options for Jenkins based on https://support.cloudbees.com/hc/en-us/articles/204859670-Java-Heap-settings-best-practice
    # and https://jenkins.io/blog/2016/11/21/gc-tuning/. Below assumes Standard DS13 v2 (8 vcpus, 56 GB memory) host
    jvm_options: "-Xms6G -Xmx12G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1"

    jenkins_timezone: '-Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/London'
    jenkins_csp_policy: '-Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src ''self''; script-src ''self'' ''unsafe-inline''; style-src ''self'' ''unsafe-inline''; font-src data:\"'
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false {{ jvm_options }} {{ jenkins_csp_policy }} {{ jenkins_timezone }}"

  roles:
    - role: ansible-terraform
    - role: azure-cli
    - role: jenkins-dependencies
    - role: jenkins
    - role: docker
    - role: nginx
