---

jenkins_external_url: 'https://build.platform.hmcts.net'
jenkins_environment_variables:
  JENKINS_VAULT_NAME: 'infra-vault'

organization_folders:
  - name: 'Contino'
    displayName: 'Contino'
    description: 'Contino'
    credentials_id: 'jenkins-ghe-api-token'
    github_api_url: 'https://api.github.com'
    repoPattern: 'moj-.*'
    jenkinsfile_path: ['Jenkinsfile_CNP']
    branchesToinclude: 'master demo'
  - name: 'HMCTS'
    displayName: 'HMCTS'
    description: 'HMCTS public repositories'
    credentials_id: 'jenkins-github-hmcts-api-token'
    github_api_url: 'https://api.github.com'
    jenkinsfile_path: ['Jenkinsfile_CNP']
    branchesToAutoBuild: '.*'
    branchesToinclude: 'master demo'

