---

- name: Install Jenkins credential using script for the {{ credential.id }} secret.
  jenkins_script:
    script: "{{ lookup('file', '{{ credential.type }}.groovy') }}"
    args:
      cred_id: "{{ credential.id }}"
      cred_desc: "{{ credential.description}}"
      cred_user: "{{ credential.username | default('') }}"
      cred_secret: "{{ credential.password | default('') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  become_user: "{{jenkins_process_user}}"
  register: result
  until: result is succeeded
