---
- name: Render {{ credential.id }} credential
  template:
    src: "create-credential.groovy"
    dest: "/tmp/jenkins-credentials/{{ credential.id }}.groovy"
    mode: 0440
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  register: credential_template_task

#- name: Configure credential
#  shell: >
#    {{ jenkins_role_cli_command }}  \
#     groovy "/tmp/jenkins-credentials/{{ credential.id }}.groovy" \
#     --username {{jenkins_admin_username}} \
#     --password {{jenkins_admin_password}}
#  args:
#    warn: no
#  when: credential_template_task.changed

- name: Install Jenkins credential using password.
  jenkins_script:
    script: "echo '/tmp/jenkins-credentials/{{ credential.id }}.groovy'"
#    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
#    validate_certs: no
  become_user: "{{jenkins_process_user}}"
  register: result
  until: result|succeeded
  ignore_errors: yes
  when: credential_template_task.changed


#  until: result | success
#  retries: 10
#  delay: 5
#  ignore_errors: yes

