---

- include_tasks: credential.yml
  loop_control:
    loop_var: credential
  with_items:
    - "{{ jenkins_credentials }}"
  when: jenkins_credentials
  notify:
  - restart jenkins
  - wait for jenkins to start
  - Check Jenkins is started

- meta: flush_handlers