---
- name: Render {{ credential.id }} credential
  template:
    src: "create-credential.groovy"
    dest: "/tmp/jenkins-credentials/{{ credential.id }}.groovy"
    mode: 0440
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  register: credential_template_task


- name: Install Jenkins credential using script.
  jenkins_script:
    script: "echo '/tmp/jenkins-credentials/{{ credential.id }}.groovy'"
#    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
#    validate_certs: no
  become_user: "{{jenkins_process_user}}"
  register: result
  until: result|succeeded
  ignore_errors: yes
  when: credential_template_task.changed

