---

- name: Create {{ folder.name }} organization folder job
  jenkins_job:
    config: "{{ lookup('template', 'templates/github-folder-multi-branch.xml.j2') }}"
    name: "{{ folder.name }}"
    password: "{{jenkins_admin_password}}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    user: "{{jenkins_admin_username}}"
  become: yes
  become_user: "{{jenkins_process_user}}"
  register: result
  until: result|succeeded
