---

#- set_fact:
#   this_folder_dir: "{{ jenkins_home }}/jobs/{{ folder.name }}"
#  tags:
#    - orgs-folders
#
#- set_fact:
#   this_folder_full_path: "{{ this_folder_dir }}/config.xml"
#  tags:
#    - orgs-folders

#- name: "Ensure {{ folder.name }} {{ this_folder_dir }} folder job exists"
#  file:
#    state: directory
#    path: "{{ this_folder_dir }}"
#    owner: "{{ jenkins_process_user }}"
#    group: "{{ jenkins_process_group }}"
#    mode: 0775
#  tags:
#    - orgs-folders

#- name: Render {{ folder.name }} folder job config xml
#  template:
#    src: "{{ folder.template | default(template) }}"
#    dest: "{{ this_folder_full_path }}"
#    owner: "{{ jenkins_process_user }}"
#    group: "{{ jenkins_process_group }}"
#  register: folder_config_file
#  tags:
#    - orgs-folders

- name: Create {{ folder.name }} organization folder job
  jenkins_job:
    config: "{{ lookup('template', 'templates/github-folder-multi-branch.xml.j2') }}"
    name: "{{ folder.name }}"
    password: "{{jenkins_admin_password}}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    user: "{{jenkins_admin_username}}"
  become: yes
  become_user: "{{jenkins_process_user}}"
  register: result
  until: result|succeeded
  ignore_errors: yes

#- name: Create {{ folder.name }} organization folder job
#  jenkins_job:
#    config: "{{ this_folder_full_path }}"
#    name: "{{ folder.name }}"
#    password: "{{jenkins_admin_password}}"
#    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
#    user: "{{jenkins_admin_username}}"
#  become: yes
#  become_user: "{{jenkins_process_user}}"
#  when: folder_config_file.changed
#  register: result
#  until: result|succeeded
#  ignore_errors: yes
#  tags:
#    - orgs-folders



