---

- set_fact:
   this_job_dir: "{{ jenkins_home }}/jobs/{{ job.name }}"
  tags:
    - jenkins-jobs
- set_fact:
   this_job_full_path: "{{ this_job_dir }}/config.xml"

- name: "Ensure {{ job.name }} {{ this_job_dir }} job folder exists"
  file:
    state: directory
    path: "{{ this_job_dir }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Render {{ job.name }} job xml
  template:
    src: "{{ job.template | default(template) }}"
    dest: "{{ this_job_full_path }}.template"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  register: job_template_file


- name: Create {{ job.name }} job
  jenkins_job:
    config: "{{ this_job_full_path }}.template"
    name: "{{ job.name }}"
    password: "{{jenkins_admin_password}}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    user: "{{jenkins_admin_username}}"
  become: yes
  become_user: "{{jenkins_process_user}}"
  when: job_template_file.changed
  register: result
  until: result|succeeded
  ignore_errors: yes