---

- name: Create pipeline jobs
  include_tasks: job.yml
  vars:
    template: "pipeline.xml.j2"
  loop_control:
    loop_var: job
  with_items:
    - "{{ pipeline_jobs }}"
  when: pipeline_jobs
  notify:
  - restart jenkins
  - wait for jenkins to start
  - Check Jenkins is started

- meta: flush_handlers
