---

- name: "Template jenkins.model.JenkinsLocationConfiguration.xml config file"
  template:
    src: "jenkins.model.JenkinsLocationConfiguration.xml.j2"
    dest: "{{ jenkins_home}}/jenkins.model.JenkinsLocationConfiguration.xml"
    owner: jenkins
    group: jenkins
    mode: 0664

- name: "Template org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultBuildWrapper.xml config file"
  template:
    src: "org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultBuildWrapper.xml.j2"
    dest: "{{ jenkins_home}}/org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultBuildWrapper.xml"
    owner: jenkins
    group: jenkins
    mode: 0664

- name: "Template jenkins.plugins.slack.SlackNotifier.xml config file"
  template:
    src: "jenkins.plugins.slack.SlackNotifier.xml.j2"
    dest: "{{ jenkins_home}}/jenkins.plugins.slack.SlackNotifier.xml"
    owner: jenkins
    group: jenkins
    mode: 0664

- name: "Template github-plugin-configuration.xml config file"
  template:
    src: "github-plugin-configuration.xml.j2"
    dest: "{{ jenkins_home}}/github-plugin-configuration.xml"
    owner: jenkins
    group: jenkins
    mode: 0664
