---

- name: "Template config.xml main config file"
  template:
    src: "templates/config.xml.j2"
    dest: "{{ jenkins_home}}/config.xml.possible"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0664
  register: jenkins_config_xml_template

- name: "Apply config.xml if changed"
  command: cp -f {{ jenkins_home}}/config.xml.possible {{ jenkins_home}}/config.xml
  when: jenkins_config_xml_template.changed
  notify:
    - restart jenkins
    - wait for jenkins to start

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
