---
- name: Add Global Pipeline Libraries
  jenkins_script:
    script: "{{ lookup('template', 'global-pipeline-library.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: result
  until: result|succeeded
  ignore_errors: yes
  loop_control:
    loop_var: global_lib
  with_items: "{{ jenkins_global_pipeline_libraries }}"
  when: jenkins_global_pipeline_libraries
  notify:
  - restart jenkins
  - wait for jenkins to start
  - Check Jenkins is started

- meta: flush_handlers
