---

- name: "Set proxy config for Jenkins"
  copy:
    src: "templates/proxy.xml.j2"
    dest: "{{ jenkins_home }}/proxy.xml"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
  notify:
    - restart jenkins
    - wait for jenkins to start
