- name: Store Jenkins Azure Service Principal credentials
  jenkins_script:
    script: "{{ lookup('template', 'push-credentials.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: result
  until: result is succeeded
  ignore_errors: yes
  notify:
  - restart jenkins
  - wait for jenkins to start
  - Check Jenkins is started
  when: jenkins_subscription_id is defined

- name: Read API key
  jenkins_script:
    script: "{{ lookup('template', 'read_token_api.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: result
#- debug: var=result.stdout
- set_fact: jenkins_admin_token=result

- meta: flush_handlers