- name: Store Jenkins Azure Service Principal credentials
  jenkins_script:
    script: "{{ lookup('template', 'push-credentials.groovy.j2') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: result
  until: result|succeeded
  ignore_errors: yes
