- name: Store Jenkins Azure Service Principal credentials
  jenkins_script:
    script: "{{ lookup('template', 'push-credentials.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: result
  until: result|succeeded
  ignore_errors: yes

- name: Read API key
  jenkins_script:
    script: "{{ lookup('template', 'read_token_api.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
  register: result
#- debug: var=result.stdout
- set_fact: jenkins_admin_token=result
- debug: var={{jenkins_admin_token}}
  until: result|succeeded
  ignore_errors: yes
