---
- name: Modify variables in init file
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option}}=\"\${{ item.option }} '
    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    state: present
  with_items:
      "{{ jenkins_init_changes }}"
  notify:
    - restart jenkins
    - wait for jenkins to start

- name: Set the Jenkins home directory
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_HOME=.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
  notify:
    - restart jenkins
    - wait for jenkins to start

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  notify:
    - restart jenkins
    - wait for jenkins to start


- name: Ensure jenkins_home {{ jenkins_home }} exists
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx

- name: Create directory {{ jenkins_home }}/.ssh
  file:
    path: "{{ jenkins_home }}/.ssh"
    state: directory
    owner: jenkins
    group: jenkins
    mode: u+rwx

- name: Add ssh key to {{ jenkins_home }}/.ssh
  copy:
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      {{ jenkins_ssh_priv_key | regex_replace(' ', '\n') }}
      -----END RSA PRIVATE KEY-----
    dest: "{{ jenkins_home }}/.ssh/id_rsa"
    owner: jenkins
    group: jenkins
    mode: 0600
  when: jenkins_ssh_priv_key is defined

- name: Create known_hosts file with github host key
  copy:
    src: files/github-known_hosts
    dest: "{{ jenkins_home }}/.ssh/known_hosts"
    group: jenkins
    owner: jenkins
    mode: 600

- name: Create custom init scripts directory.
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Trigger handlers immediately in case Jenkins was installed
  meta: flush_handlers

- name: Increase Jenkins Security
  template:
    src: templates/disable-jenkins-cli.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/disable-jenkins-cli.groovy"
    group: jenkins
    owner: jenkins
    mode: 0700
