---

- name: "Ensure jenkins home .ssh/ exists"
  file:
    path: "{{ jenkins_home_task.stdout }}/.ssh"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0700

- name: "Set up SSH client config"
  template:
    src: ssh-config.j2
    dest: "{{ jenkins_home_task.stdout }}/.ssh/config"
    owner: jenkins
    group: jenkins
    mode: 0600


