---

- name: Ensure default Red Hat Docker packages are removed
  yum:
    name: {{ item }}
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine

- name: Install required dependencies
  yum:
    name: {{ item }}
    state: present
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: Enable Docker CE respository
  yum_repository:
    name: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker CE
  yum:
    name: docker-ce
    state: present

- name: Provide socket ownership configuration to allow dockerroot group users to use Docker
  template:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"
    mode: 0644
    owner: root
    group: root

- name: Add Jenkins to dockerroot group
  user:
    name: jenkins
    groups: dockerroot
    append: yes

- name: Start and enable Docker service within systemd
  systemd:
    name: docker
    state: started
    enabled: yes
