---

- name: "Yarn | Install RPM repository"
  become: 'yes'
  become_user: root
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    owner: root
    mode: 0644

- name: "NodeJs | Get setup script"
  get_url:
    url: https://rpm.nodesource.com/setup_8.x
    dest: /tmp/node_setup
    owner: root
    mode: 750
  register: getting_setup
  notify:
    - NodeJs Run setup script

- name: "Install epel-release"
  yum:
    name: epel-release
    state: installed

- meta: flush_handlers

- name: "Install dependencies from yum"
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ jenkins_role_yum_packages }}"
  ignore_errors: 'yes'

- name: "Install dependencies from pip"
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ jenkins_role_pip_packages }}"
  ignore_errors: 'yes'
